"use client";

import { AppShell } from "@/components/shell";
import { Badge, Button, Card, PageSkeleton } from "@/components/ui";
import { api } from "@/lib/api";
import { inr } from "@/lib/utils";
import { motion } from "framer-motion";
import { ArrowRight, Sparkles } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

type Rec = {
  title: string; reason: string; expected_benefit: string;
  priority: "high" | "medium" | "low"; est_revenue_uplift: number; uplift_pct: number;
};

export default function RecommendationsPage() {
  const [recs, setRecs] = useState<Rec[] | null>(null);

  useEffect(() => {
    api.get<{ recommendations: Rec[] }>("/api/insights/recommendations").then((d) => setRecs(d.recommendations)).catch(() => {});
  }, []);

  if (!recs) {
    return (
      <AppShell title="Recommendation Center"><PageSkeleton /></AppShell>
    );
  }

  return (
    <AppShell title="Recommendation Center">
      <p className="mb-5 max-w-2xl text-sm text-ink-2">
        Generated by the twin engine from your live KPIs and risk scan. Each recommendation shows why, the expected benefit,
        and the estimated monthly revenue impact — test any of them in the <Link href="/simulator" className="font-medium text-brand hover:underline">Simulator</Link> first.
      </p>
      <div className="grid gap-4 md:grid-cols-2">
        {recs.map((r, i) => (
          <motion.div key={r.title} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.07 }}>
            <Card className="flex h-full flex-col">
              <div className="flex items-start justify-between gap-2">
                <div className="flex items-center gap-2.5">
                  <div className="rounded-xl bg-brand-soft p-2 text-brand"><Sparkles size={16} /></div>
                  <p className="font-semibold leading-snug">{r.title}</p>
                </div>
                <Badge tone={r.priority === "high" ? "critical" : r.priority === "medium" ? "medium" : "low"}>{r.priority} priority</Badge>
              </div>
              <p className="mt-3 text-sm leading-relaxed text-ink-2"><span className="font-medium text-ink">Why:</span> {r.reason}</p>
              <p className="mt-2 text-sm leading-relaxed text-ink-2"><span className="font-medium text-ink">Benefit:</span> {r.expected_benefit}</p>
              <div className="mt-auto flex items-center justify-between pt-4">
                {r.est_revenue_uplift > 0 ? (
                  <p className="text-sm font-bold text-[var(--delta-good)]">≈ {inr(r.est_revenue_uplift)}/mo <span className="font-normal text-muted">(+{r.uplift_pct}%)</span></p>
                ) : (
                  <p className="text-sm text-muted">Margin-protecting move</p>
                )}
                <Link href="/simulator">
                  <Button variant="outline" size="sm">Simulate <ArrowRight size={13} /></Button>
                </Link>
              </div>
            </Card>
          </motion.div>
        ))}
      </div>
    </AppShell>
  );
}
